### ISSUE TITLE
FlutterBeepPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by M1Joe** [trietho/flutter_beep#2]
I'm excited for this package, but I receive these warnings when using the package for Android.  Is this something we can fix easily?

Note: C:\Users\Joe.DESKTOP-4BRHLNO\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_beep-0.2.0\android\src\main\java\com\gonoter\flutter_beep\FlutterBeepPlugin.java uses or overrides a deprecated API.

**Comment by TritiumCo** [comment]
I have the same warning...
